version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - database.env # configure mysql
volumes:
  db_data:
